### ISSUE TITLE
Using the {loupee_value} twice?

### ISSUE THREAD

**Issue by paulalden** [danott/ee-loopee#6]
I'm sorry if this is a stupid question, but when I use {loupee_value}, or whatever variable name is set in the `as="var"`, the tag breaks the page. Is this a known issue? Can we only use the loop value once?

**Comment by danott** [comment]
Howdy @prwhitehead. That's not a stupid question at all! This is the first time I've ever heard of such breakage.

I don't have anything running in ExpressionEngine these days, so I'm not able to try to replicate the issue.

Is it specifically the value `as="var"` that breaks things? I'm wondering if that could be because `var` is a [PHP keyword](http://php.net/manual/en/reserved.keywords.php)?

Could you paste an excerpt of your code here, and maybe that could help?

**Comment by paulalden** [comment]
Sorry, `as="var"` was just an example of the use case. I was using a variety of terms to ensure that it wasn't the keyword. 

It's very likely that due to my lack of understanding regarding the inner workings of EE's parse order the fault was mine.

**Comment by danott** [comment]
Closing this issue after 6 months of inactivity.
